name: Publish WinForm App

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DynamicWallpaper.sln 
      Project_Name: DynamicWallpaper.csproj

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=Release /m
    - name: Publish app
      run: msbuild $env:Project_Name /p:Configuration=Release /p:PublishProfile=FolderProfile /m
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DynamicWallpaper App Release
        path: bin/Release/net6.0-windows/publish/win-x86
    - name: Create tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}
        release_name: Release ${{ github.event.inputs.tag }}
        body: |
            ${{ github.event.release.body }}
        draft: false
        prerelease: false
