name: Publish WinForm App

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DynamicWallpaper.sln 
      Project_Name: src/DynamicWallpaper.csproj
      publish_dir: bin/release/publish
      msi_dir: bin/release/msi
      wixtool_dir: C:\wixtoolset\
      

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2


    - name: Publish app
      run: dotnet publish $env:Project_Name -c Release -r win-x86 -p:PublishReadyToRun=true -p:SelfContained=true -p:PublishSingleFile=true -p:PublishDir=../${{ env.publish_dir }}
    - name: Install wixtoolset
      run: |
        Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip' -OutFile 'wix311-binaries.zip'
        Expand-Archive -Path 'wix311-binaries.zip' -DestinationPath ${{ env.wixtool_dir }}
        
    - name: Create MSI installer
      run: |
        ${{ env.wixtool_dir }}/candle $env:msi_dir/DynamicWallpaper.wxs
        ${{ env.wixtool_dir }}/light $env:msi_dir/DynamicWallpaper.wixobj -o $env:msi_dir/DynamicWallpaper.msi
    - name: Zip files
      run: |
        Compress-Archive -Path ${{ env.publish_dir }}/* -DestinationPath ${{ env.publish_dir }}/DynamicWallpaper.zip
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.publish_dir }}/DynamicWallpaper.zip
        asset_name: DynamicWallpaper.zip
        asset_content_type: application/zip
    - name: Upload MSI installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.msi_dir }}/DynamicWallpaper.msi
        asset_name: DynamicWallpaper.msi
        asset_content_type: application/octet-stream
