name: Publish WinForm App

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DynamicWallpaper.sln 
      Project_Name: src/DynamicWallpaper.csproj
      wixProject_Name: MsiPackage/DynamicWallpaper.Setup.wixproj
      publish_dir: bin/release/publish
      msi_dir: bin/msi
      

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup wix
      run: dotnet tool install --global wix --version 4.0.0 
      
    - name: Check wix Version
      run: wix --version


    - name: Publish app
      run: dotnet publish $env:Project_Name -c Release -r win-x86 -p:PublishReadyToRun=true -p:SelfContained=true -p:PublishSingleFile=true -p:PublishDir=../${{ env.publish_dir }}

        
    - name: Create MSI installer
      run: |
        dotnet build $env.wixProject_Name -o ../${{ env.msi_dir }}
        dir ../bin/
        dir ../${{ env.msi_dir }}
    - name: Zip files
      run: |
        Compress-Archive -Path ${{ env.publish_dir }}/* -DestinationPath ${{ env.publish_dir }}/DynamicWallpaper.zip
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.publish_dir }}/DynamicWallpaper.zip
        asset_name: DynamicWallpaper.zip
        asset_content_type: application/zip
    - name: Upload MSI installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.msi_dir }}/DynamicWallpaper.Setup.msi
        asset_name: DynamicWallpaper.Setup.msi
        asset_content_type: application/octet-stream
